services:
  app:
    build: .
    platform: linux/amd64 # <--- Add this line
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: npm run dev

  db:
    image: postgres:14-alpine
    platform: linux/amd64 # <--- Add this line
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    platform: linux/amd64 # <--- Add this line
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: